name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR file
        run: mvn clean install -DskipTests

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t devraman/courses-api:latest .
          docker push devraman/courses-api:latest

      - name: Run Docker Container
        run: |
          docker run -e SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
                     -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USER }} \
                     -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
                     -p 8080:8080 devraman/courses-api:latest
